### PR TITLE
ember-power-select update

### PR DESCRIPTION
**Pull request by harmaty**

### CODE REVIEW

**Comment by harmaty** [comment]
There were issues with IE, which have been fixed in recent versions of ember-power-select

**Comment by knownasilya** [comment]
Could you update this to use beta.14 so it solves the createElement issue in Ember 2.8

**Comment by knownasilya** [comment]
@cibernox Ping 👍

**Comment by cibernox** [comment]
@knownasilya I missed this. Can you just update it to the latest stable (1.5.0)? Then I'll merge and release it.

**Pull request merged**
