### PR TITLE
Update Power Select

### LINKED ISSUE #1: search term not cleared after select
See https://github.com/cibernox/ember-power-select/issues/314

I'd have linked to the PR, but unsure which one.. probably just need to update the power select dependency.

### PR DESCRIPTION
**Pull request by knownasilya**
Fixes #1

Also removes duplicate ember-sortable deps, and the unnecessary ember-data dep.

Looks like it works fine.

### CODE REVIEW

**Comment by knownasilya** [comment]
This is ready for merge.

**Comment by cibernox** [comment]
So, updating the dependency make the component to clear the search, correct?

**Comment by knownasilya** [comment]
Yes sir. Worked just fine in my app.

**Comment by cibernox** [comment]
Published as 0.1.4.

I'm actually glad that someone is using this little thing I did just for live demo.

**Comment by knownasilya** [comment]
It's necessary for ambitious applications :+1:

**Pull request merged**
